name: Build

on:
  push:

permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
          
      - shell: bash
        run: |
          echo -n "[" > courses.json && \
          find courses/*.json  -printf '"%p",' >> courses.json && \
          sed -i '$ s/,$//' courses.json && echo "]" >> courses.json

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
